//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillChild
    {
        public int BillChildid { get; set; }
        public Nullable<int> BillMasterid { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> FcAmount { get; set; }
        public Nullable<int> LcAmount { get; set; }
        public Nullable<int> EqUsd { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
