//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string RelationType { get; set; }
        public string RelationName { get; set; }
        public Nullable<int> LegalIDType { get; set; }
        public string LegalIdno { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> Profession { get; set; }
        public Nullable<int> Dessignation { get; set; }
        public string OtherDesignation { get; set; }
        public string LandLineNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
