//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int id { get; set; }
        public string MenuName { get; set; }
        public string URL { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
