//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherChild
    {
        public int VoucherChildId { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string AccountCode { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> DrCrId { get; set; }
        public Nullable<int> FcAmount { get; set; }
        public Nullable<int> LcAmount { get; set; }
        public Nullable<int> EqUsd { get; set; }
    }
}
